# application name
spring.application.name='URL Shortener'

## Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# devtools
server.port=${PORT}
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.add-properties=true

# log level debug
logging.level.com.shorturl='DEBUG'
logging.file.name=[dev]-shortUrl.log

# log for postgres and jdbc
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.postgresql=DEBUG

# db creds
spring.datasource.url=jdbc:${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver